// src/services/prolog.service.js
// Generates a Prolog fact file from MongoDB data, runs it via SWI-Prolog,
// parses the output, and saves match results back to MongoDB.

const { execFile } = require("child_process");
const fs            = require("fs");
const path          = require("path");
const os            = require("os");

const Candidate  = require("../models/Candidate");
const Internship = require("../models/Internship");
const Match      = require("../models/Match");

// ─── 1. Generate .pl file from live MongoDB data ────────────────────────────
function generatePrologFile(candidates, internships) {
  const lines = [];
  lines.push("% ── Auto-generated by InternAI Prolog Service ──");
  lines.push(":- use_module(library(aggregate)).");
  lines.push("");

  // Candidate skills facts
  lines.push("% Candidate skills");
  for (const c of candidates) {
    const id = c._id.toString();
    for (const skill of (c.skills || [])) {
      const s = skill.toLowerCase().replace(/[^a-z0-9_]/g, "_");
      lines.push(`skill('${id}', ${s}).`);
    }
  }
  lines.push("");

  // Internship facts + required skills
  lines.push("% Internships and required skills");
  for (const i of internships) {
    const id    = i._id.toString();
    const title = i.title.replace(/'/g, "\\'");
    lines.push(`internship('${id}', '${title}').`);
    for (const skill of (i.skills || [])) {
      const s = skill.toLowerCase().replace(/[^a-z0-9_]/g, "_");
      lines.push(`requires('${id}', ${s}).`);
    }
  }
  lines.push("");

  // Rules
  lines.push("% ── Rules ──");
  lines.push(`has_skill(C, S) :- skill(C, S).`);
  lines.push("");
  lines.push(`match_count(C, E, Count) :-`);
  lines.push(`    aggregate_all(count, (requires(E, S), has_skill(C, S)), Count).`);
  lines.push("");
  lines.push(`total_required(E, Total) :-`);
  lines.push(`    aggregate_all(count, requires(E, _), Total).`);
  lines.push("");
  lines.push(`match_score(C, E, Score) :-`);
  lines.push(`    total_required(E, Total),`);
  lines.push(`    ( Total =:= 0`);
  lines.push(`    -> Score is 0.0`);
  lines.push(`    ;  match_count(C, E, Match),`);
  lines.push(`       Score is truncate((Match / Total) * 100 * 10) / 10`);
  lines.push(`    ).`);
  lines.push("");
  lines.push(`skill_gap(C, E, Missing) :-`);
  lines.push(`    requires(E, Missing),`);
  lines.push(`    \\+ has_skill(C, Missing).`);
  lines.push("");
  lines.push(`matched_skills(C, E, Matched) :-`);
  lines.push(`    findall(S, (requires(E, S), has_skill(C, S)), Matched).`);
  lines.push("");

  // Query — one line per candidate+internship pair
  lines.push("% ── Queries ──");
  lines.push(`:- forall(`);
  lines.push(`    (internship(IId, _), skill(CId, _)),`);
  lines.push(`    (`);
  lines.push(`        match_score(CId, IId, Score),`);
  lines.push(`        Score > 0,`);
  lines.push(`        findall(S, skill_gap(CId, IId, S), Gap),`);
  lines.push(`        matched_skills(CId, IId, Matched),`);
  lines.push(`        format(atom(GapAtom),     '~w', [Gap]),`);
  lines.push(`        format(atom(MatchedAtom), '~w', [Matched]),`);
  lines.push(`        format('~w|~w|~w|~w~n', [CId, IId, Score, GapAtom, MatchedAtom])`);
  lines.push(`    )`);
  lines.push(`   ).`);

  return lines.join("\n");
}

// ─── 2. Run SWI-Prolog and capture output ───────────────────────────────────
function runProlog(plFile) {
  return new Promise((resolve, reject) => {
    // Try common SWI-Prolog binary names (includes Windows paths)
    const isWin = process.platform === "win32";
    const bins  = isWin
      ? [
          "swipl",
          "C:\\Program Files\\swipl\\bin\\swipl.exe",
          "C:\\Program Files (x86)\\swipl\\bin\\swipl.exe",
        ]
      : ["swipl", "pl", "prolog"];
    let tried = 0;

    const tryNext = () => {
      if (tried >= bins.length) {
        return reject(new Error("SWI-Prolog not found. Install it with: apt install swi-prolog"));
      }
      const bin = bins[tried++];
      execFile(
        bin,
        ["-g", "halt", "-t", "halt", plFile],
        { timeout: 30000 },
        (err, stdout, stderr) => {
          if (err && err.code === "ENOENT") return tryNext();
          if (err) return reject(new Error(`Prolog error: ${stderr || err.message}`));
          resolve(stdout);
        }
      );
    };
    tryNext();
  });
}

// ─── 3. Parse Prolog output lines ───────────────────────────────────────────
// Format: candidateId|internshipId|score|[gap1,gap2]|[match1,match2]
function parseOutput(output) {
  const results = [];
  for (const line of output.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("%") || trimmed.startsWith("?")) continue;
    const parts = trimmed.split("|");
    if (parts.length < 4) continue;

    const [candidateId, internshipId, scoreStr, gapStr, matchedStr] = parts;
    const score = parseFloat(scoreStr) || 0;
    if (score <= 0) continue;

    // Parse Prolog list format [item1,item2] -> ['item1', 'item2']
    const parseList = (s = "") =>
      s.replace(/[\[\]]/g, "").split(",").map(x => x.trim()).filter(Boolean);

    results.push({
      candidateId:   candidateId.trim(),
      internshipId:  internshipId.trim(),
      score,
      skillGaps:     parseList(gapStr),
      matchedSkills: parseList(matchedStr),
    });
  }
  return results;
}

// ─── 4. Save results to MongoDB Match collection ────────────────────────────
async function saveMatches(results, internships) {
  let created = 0, updated = 0;

  // Build internship -> companyId map
  const internshipMap = {};
  for (const i of internships) internshipMap[i._id.toString()] = i;

  for (const r of results) {
    const internship = internshipMap[r.internshipId];
    if (!internship) continue;

    const filter = { candidateId: r.candidateId, internshipId: r.internshipId };
    const update = {
      candidateId:   r.candidateId,
      companyId:     internship.companyId,
      internshipId:  r.internshipId,
      role:          internship.title,
      aiScore:       r.score,
      matchedSkills: r.matchedSkills,
      skillGaps:     r.skillGaps,
      reason:        `Prolog AI matched ${r.matchedSkills.length} of ${r.matchedSkills.length + r.skillGaps.length} required skills.`,
      status:        "Pending",
      updatedAt:     new Date(),
    };

    const existing = await Match.findOne(filter);
    if (existing) {
      await Match.findByIdAndUpdate(existing._id, update);
      updated++;
    } else {
      await Match.create({ ...update, createdAt: new Date() });
      created++;
    }
  }
  return { created, updated };
}

// ─── 5. Main exported function ───────────────────────────────────────────────
async function runPrologMatching() {
  console.log("[Prolog] Starting matching engine…");

  // Fetch data from MongoDB
  const [candidates, internships] = await Promise.all([
    Candidate.find({ status: "Active" }),
    Internship.find({ status: "Open", approvalStatus: "approved" }),
  ]);

  console.log(`[Prolog] Loaded ${candidates.length} candidates, ${internships.length} internships`);

  if (!candidates.length || !internships.length) {
    return { success: true, message: "No data to match", created: 0, updated: 0 };
  }

  // Write temp .pl file
  const plContent = generatePrologFile(candidates, internships);
  const plFile    = path.join(os.tmpdir(), `internai_match_${Date.now()}.pl`);
  fs.writeFileSync(plFile, plContent, "utf8");
  console.log(`[Prolog] Wrote fact file: ${plFile}`);

  try {
    // Run Prolog
    const output  = await runProlog(plFile);
    const results = parseOutput(output);
    console.log(`[Prolog] Got ${results.length} match results`);

    // Save to DB
    const saved = await saveMatches(results, internships);
    console.log(`[Prolog] Saved — created: ${saved.created}, updated: ${saved.updated}`);

    return { success: true, results: results.length, ...saved };
  } finally {
    // Clean up temp file
    try { fs.unlinkSync(plFile); } catch {}
  }
}

// ─── 6. Preview only (no DB write) — for testing ────────────────────────────
async function previewPrologFile() {
  const [candidates, internships] = await Promise.all([
    Candidate.find({ status: "Active" }).limit(5),
    Internship.find({ status: "Open" }).limit(5),
  ]);
  return generatePrologFile(candidates, internships);
}

module.exports = { runPrologMatching, previewPrologFile };
